spring.application.name=boot-legacy
server.port=${PORT:8080}
# view resolver 설정
# controller -> string -> (prefix)string(suffix) -> 템플릿 호출
# webapp -> jasper 의존성이 알아서 이 경로를 감지
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp